"""Shared Pydantic schemas describing structured agent responses."""

from __future__ import annotations

from typing import Any, List, Optional, Dict

from pydantic import BaseModel, ConfigDict, Field, model_validator


class OutlineChapterPayload(BaseModel):
    """Single chapter entry returned by the outline agent."""

    number: int = Field(ge=1)
    title: str = Field(default="")
    description: Optional[str] = None
    estimated_duration_minutes: Optional[int] = Field(default=None, ge=0)
    files_covered: List[str] = Field(default_factory=list)
    learning_objectives: List[str] = Field(default_factory=list)
    topics: List[str] = Field(default_factory=list)

    model_config = ConfigDict(extra="allow")
    
    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: Any, handler: Any) -> Dict[str, Any]:
        """Override JSON schema generation to enforce additionalProperties: false for OpenAI structured outputs."""
        json_schema = handler(core_schema)
        # Recursively set additionalProperties: false for all object schemas
        if isinstance(json_schema, dict):
            # Ensure root schema has type: "object" if it has properties
            if "properties" in json_schema and json_schema.get("type") != "object":
                json_schema["type"] = "object"
            _set_additional_properties_false(json_schema)
        return json_schema

    @model_validator(mode="before")
    @classmethod
    def _coerce_numeric_fields(cls, values: Any) -> Any:
        if isinstance(values, dict):
            data = dict(values)
            if "number" in data:
                try:
                    data["number"] = int(data["number"])
                except (TypeError, ValueError):
                    data["number"] = 0
            if "estimated_duration_minutes" in data:
                try:
                    data["estimated_duration_minutes"] = int(
                        data["estimated_duration_minutes"]
                    )
                except (TypeError, ValueError):
                    data["estimated_duration_minutes"] = None
            return data
        return values


class OutlineAgentResponse(BaseModel):
    """Structured outline payload enforced for agent responses."""

    chapters: List[OutlineChapterPayload] = Field(default_factory=list)
    depth_tier: Optional[str] = None
    total_estimated_duration_minutes: Optional[int] = Field(default=None, ge=0)
    total_chapters: Optional[int] = Field(default=None, ge=0)
    raw_outline: Optional[str] = None

    model_config = ConfigDict(extra="allow")
    
    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: Any, handler: Any) -> Dict[str, Any]:
        """Override JSON schema generation to enforce additionalProperties: false for OpenAI structured outputs."""
        json_schema = handler(core_schema)
        # Recursively set additionalProperties: false for all object schemas
        if isinstance(json_schema, dict):
            # Ensure root schema has type: "object" if it has properties
            if "properties" in json_schema and json_schema.get("type") != "object":
                json_schema["type"] = "object"
            _set_additional_properties_false(json_schema)
        return json_schema

    @model_validator(mode="after")
    def _populate_totals(self) -> "OutlineAgentResponse":
        chapter_count = self.total_chapters or len(self.chapters)
        minutes = self.total_estimated_duration_minutes
        if minutes is None:
            minutes = sum(
                max(chapter.estimated_duration_minutes or 0, 0)
                for chapter in self.chapters
            )
        object.__setattr__(self, "total_chapters", chapter_count)
        object.__setattr__(
            self, "total_estimated_duration_minutes", minutes if minutes >= 0 else 0
        )
        return self


class ScriptAgentResponse(BaseModel):
    """Narration script payload generated by the script agent."""

    chapter_number: Optional[int] = Field(default=None, ge=1)
    chapter_title: Optional[str] = None
    script: str = Field(default="")
    summary: Optional[str] = None

    model_config = ConfigDict(extra="allow")
    
    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: Any, handler: Any) -> Dict[str, Any]:
        """Override JSON schema generation to enforce additionalProperties: false for OpenAI structured outputs."""
        json_schema = handler(core_schema)
        # Recursively set additionalProperties: false for all object schemas
        if isinstance(json_schema, dict):
            # Ensure root schema has type: "object" if it has properties
            if "properties" in json_schema and json_schema.get("type") != "object":
                json_schema["type"] = "object"
            _set_additional_properties_false(json_schema)
        return json_schema

    @model_validator(mode="after")
    def _trim_script(self) -> "ScriptAgentResponse":
        object.__setattr__(self, "script", self.script.strip())
        return self


class AudioAgentResponse(BaseModel):
    """Audio synthesis payload returned by the audio agent."""

    chapter_number: Optional[int] = Field(default=None, ge=1)
    audio_url: str
    local_path: Optional[str] = None
    duration_seconds: Optional[int] = Field(default=None, ge=0)
    voice: Optional[str] = None

    model_config = ConfigDict(extra="allow")
    
    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: Any, handler: Any) -> Dict[str, Any]:
        """Override JSON schema generation to enforce additionalProperties: false for OpenAI structured outputs."""
        json_schema = handler(core_schema)
        # Recursively set additionalProperties: false for all object schemas
        if isinstance(json_schema, dict):
            # Ensure root schema has type: "object" if it has properties
            if "properties" in json_schema and json_schema.get("type") != "object":
                json_schema["type"] = "object"
            _set_additional_properties_false(json_schema)
        return json_schema


def _set_additional_properties_false(schema: Dict[str, Any]) -> None:
    """Recursively set additionalProperties: false for all object schemas."""
    # Set additionalProperties: false for objects (either explicit type or implicit via properties)
    schema_type = schema.get("type")
    has_properties = "properties" in schema
    
    if schema_type == "object" or (has_properties and schema_type is None):
        schema["additionalProperties"] = False
    
    # Handle nested objects in properties
    if "properties" in schema:
        for prop_schema in schema["properties"].values():
            if isinstance(prop_schema, dict):
                _set_additional_properties_false(prop_schema)
    
    # Handle nested objects in items (for arrays)
    if "items" in schema:
        if isinstance(schema["items"], dict):
            _set_additional_properties_false(schema["items"])
        elif isinstance(schema["items"], list):
            for item in schema["items"]:
                if isinstance(item, dict):
                    _set_additional_properties_false(item)
    
    # Handle nested objects in definitions/oneOf/allOf/anyOf
    for key in ["oneOf", "allOf", "anyOf"]:
        if key in schema:
            for item in schema[key]:
                if isinstance(item, dict):
                    _set_additional_properties_false(item)
    
    # Handle $ref definitions
    if "$defs" in schema:
        for def_schema in schema["$defs"].values():
            if isinstance(def_schema, dict):
                _set_additional_properties_false(def_schema)
